const GET_CHARITIES = "GET_CHARITIES"
const ADD_CHARITY = "ADD_CHARITIES"
const EDIT_CHARITY = "ADD_CHARITY"
const DELETE_CHARITY = "DELETE_CHARITY"
//need a set or undo kind of action type for charity?

const COMMENT_FORM = "COMMENT_FORM"
const EDIT_COMMENT = "EDIT_COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"

const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"

export {
  GET_CHARITIES
  ADD_CHARITY
  EDIT_CHARITY
  DELETE_CHARITY
  COMMENT_FORM
  EDIT_COMMENT
  DELETE_COMMENT
  SET_CURRENT_USER
  CLEAR_CURRENT_USER
}

