const GET_CHARITIES = "GET_CHARITIES"
const ADD_CHARITY = "ADD_CHARITIES"
const EDIT_CHARITY = "ADD_CHARITY"
const DELETE_CHARITY = "DELETE_CHARITY"
const SET_SELECTED_CHARITY = "SET_SELECTED_CHARITY"
const UNSET_CHARITY = "UNSET_CHARITY"

const COMMENT_FORM_UPDATE = "COMMENT_FORM_UPDATE"
const SET_COMMENT = "SET_COMMENT"
const SET_FORM_DATA_EDIT_COMMENT = "SET_FORM_DATA_EDIT_COMMENT"
const RESET_FORM_DATA_COMMENT = "RESET_FORM_DATA_COMMENT"
const EDIT_COMMENT = "EDIT_COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"

const FILTER_FORM_CHANGE = "FILTER_FORM_CHANGE"

const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"

export {
  GET_CHARITIES,
  ADD_CHARITY,
  EDIT_CHARITY,
  DELETE_CHARITY,
  SET_SELECTED_CHARITY,
  UNSET_CHARITY,
  COMMENT_FORM_UPDATE,
  SET_COMMENT,
  SET_FORM_DATA_EDIT_COMMENT,
  RESET_FORM_DATA_COMMENT,
  EDIT_COMMENT,
  DELETE_COMMENT,
  FILTER_FORM_CHANGE,
  SET_CURRENT_USER,
  CLEAR_CURRENT_USER,
  BEGIN_AUTH,
  COMPLETE_AUTH,
}

