export const LOGIN_NEW_USER = 'LOGIN NEW USER';
export const SIGN_UP_NEW_USER = 'SIGN UP NEW USER';
export const GET_ALL_CHARITIES = 'GET ALL CHARITIES';
export const DELETE_CHARITY = 'DELETE CHARITY';
export const UPDATE_CHARITY = 'UPDATE CHARITY';
export const ADD_COMMENT = 'ADD A NEW COMMENT';
export const UPDATE_COMMENT = 'UPDATE COMMENT';
export const DELETE_COMMENT = 'DELETE A COMMENT';
export const GET_CATEGORIES = 'GET ALL CATEGORIES';
export const CURRENT_USER_CHARITIES = 'GET CURRENT USER CHARITIES';
export const GET_ALL_COMMENTS = 'GET ALL COMMENTS';
export const CHANGE_FILTER = 'CHANGE FILTER';

